backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Contact Page'
        name: 'contact'
        file: 'contact/index.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'contact' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Home Page'
        name: 'Home'
        file: 'index.html'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown'}